### ISSUE TITLE
[Bug] Alpine 3.17 and PHP81

### ISSUE THREAD

**Issue by mhzawadi** [InvoicePlane/InvoicePlane#909]
## Expected Behavior
invoiveplane works 

## Current Behavior
errors from PHP

## Screenshots
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/11944327/215041416-86cef4ae-09d5-4299-af50-8930f020417f.png">

## Possible Solution
remove mcrypt dependacy

## Steps to Reproduce
Build docker image with alpine and PHP81

## Context (Environment)
Hello good devs 👋🏼 

I am in the process of updating my docker images to alpine v3.17 and have come to update my inviceplane image, but have many issues getting the image to run. I have 3 php modules that I cant install in alpine as they dont exsist.

- php81-mcrypt
- php81-recode
- php81-zlib

mcrypt is now not even a pecl install, as alpine doesnt have access to pecl to  install from the internet.
[My docker image repo](https://github.com/mhzawadi/invoiceplane)

## Failure Logs
```
2023-01-27 08:07:59 2023/01/27 08:07:59 [error] 15#15: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>]. in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30
2023-01-27 08:07:59 Stack trace:
2023-01-27 08:07:59 #0 /var/www/html/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}('Encountered an ...')
2023-01-27 08:07:59 #1 /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error->mapError(Object(Closure))
2023-01-27 08:07:59 #2 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse('<?php exit('No ...')
2023-01-27 08:07:59 #3 /var/www/html/index.php(20): Dotenv\Dotenv->load()
2023-01-27 08:07:59 #4 {main}
2023-01-27 08:07:59   thrown in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:07:59 127.0.0.1 - - [27/Jan/2023:08:07:59 +0000] "GET /index.php HTTP/1.1" 200 844 "-" "curl/7.87.0" "-"
2023-01-27 08:09:00 2023/01/27 08:09:00 [error] 17#17: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>]. in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30
2023-01-27 08:09:00 Stack trace:
2023-01-27 08:09:00 #0 /var/www/html/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}('Encountered an ...')
2023-01-27 08:09:00 #1 /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error->mapError(Object(Closure))
2023-01-27 08:09:00 #2 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse('<?php exit('No ...')
2023-01-27 08:09:00 #3 /var/www/html/index.php(20): Dotenv\Dotenv->load()
2023-01-27 08:09:00 #4 {main}
2023-01-27 08:09:00   thrown in /var/www/html/vendor/vlucas/phpdotenv/src/Parser/Parser.php on line 30" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:09:00 127.0.0.1 - - [27/Jan/2023:08:09:00 +0000] "GET /index.php HTTP/1.1" 200 844 "-" "curl/7.87.0" "-"
2023-01-27 08:09:10 2023/01/27 08:09:10 [error] 18#18: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 192.168.0.4, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "invoiceplane.docker.local"
2023-01-27 08:09:10 192.168.0.4 - - [27/Jan/2023:08:09:10 +0000] "GET / HTTP/1.1" 500 862 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0" "192.168.0.1"
2023-01-27 08:10:00 2023/01/27 08:10:00 [error] 16#16: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:10:00 127.0.0.1 - - [27/Jan/2023:08:10:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:10:55 2023/01/27 08:10:55 [error] 15#15: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 192.168.0.4, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "invoiceplane.docker.local"
2023-01-27 08:10:55 192.168.0.4 - - [27/Jan/2023:08:10:55 +0000] "GET / HTTP/1.1" 500 862 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0" "192.168.0.1"
2023-01-27 08:11:00 2023/01/27 08:11:00 [error] 15#15: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:11:00 127.0.0.1 - - [27/Jan/2023:08:11:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:12:00 2023/01/27 08:12:00 [error] 15#15: *13 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:12:00 127.0.0.1 - - [27/Jan/2023:08:12:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:13:00 2023/01/27 08:13:00 [error] 15#15: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:13:00 127.0.0.1 - - [27/Jan/2023:08:13:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:14:00 2023/01/27 08:14:00 [error] 15#15: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:14:00 127.0.0.1 - - [27/Jan/2023:08:14:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:15:00 2023/01/27 08:15:00 [error] 15#15: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:15:00 127.0.0.1 - - [27/Jan/2023:08:15:00 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:16:01 2023/01/27 08:16:01 [error] 15#15: *21 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:16:01 127.0.0.1 - - [27/Jan/2023:08:16:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:17:01 2023/01/27 08:17:01 [error] 15#15: *23 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:17:01 127.0.0.1 - - [27/Jan/2023:08:17:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:18:01 2023/01/27 08:18:01 [error] 15#15: *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:18:01 127.0.0.1 - - [27/Jan/2023:08:18:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:19:01 2023/01/27 08:19:01 [error] 15#15: *27 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:19:01 127.0.0.1 - - [27/Jan/2023:08:19:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:20:01 2023/01/27 08:20:01 [error] 15#15: *29 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:20:01 127.0.0.1 - - [27/Jan/2023:08:20:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:21:01 2023/01/27 08:21:01 [error] 15#15: *31 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:21:01 127.0.0.1 - - [27/Jan/2023:08:21:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:22:01 2023/01/27 08:22:01 [error] 15#15: *33 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:22:01 127.0.0.1 - - [27/Jan/2023:08:22:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:23:01 2023/01/27 08:23:01 [error] 15#15: *35 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:23:01 127.0.0.1 - - [27/Jan/2023:08:23:01 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:24:02 2023/01/27 08:24:02 [error] 15#15: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:24:02 127.0.0.1 - - [27/Jan/2023:08:24:02 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:25:02 2023/01/27 08:25:02 [error] 15#15: *39 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:25:02 127.0.0.1 - - [27/Jan/2023:08:25:02 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:26:02 2023/01/27 08:26:02 [error] 17#17: *41 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:26:02 127.0.0.1 - - [27/Jan/2023:08:26:02 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:27:02 2023/01/27 08:27:02 [error] 17#17: *43 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:27:02 127.0.0.1 - - [27/Jan/2023:08:27:02 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
2023-01-27 08:28:02 2023/01/27 08:28:02 [error] 17#17: *45 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-27 08:28:02 127.0.0.1 - - [27/Jan/2023:08:28:02 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
```

**Comment by nielsdrost7** [comment]
I'll take a look this weekend

**Comment by nielsdrost7** [comment]
Let's take it 1 error at a time:
```PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>].```
Could you open up `ipconfig.php` and put a `#` sign in front of that first line:
```#<?php exit('No direct script access allowed'); ?>```

**Comment by nielsdrost7** [comment]
I tried your `dev` branch, but didn't see any work on PHP 8.1 or InvoicePlane V1.6.0
Tried to do the updates myself on your branch (created new branch of course), but couldn't make it run.
Can you show on which branch in your repository you have these problems?

I saw a couple of things in your repository, I will give advice instead of pointing:
- I would break up the services into the php-fpm service and the nginx service
- In my Dockerfile for php-fpm I would go for a pre-build image of  php-fpm with alpine: `FROM php:8.1.14-fpm-alpine3.17`
- Did you get your image to work with nginx AND php-fpm? I had troubles with the config files in `/etc/(php version)/php-fpm.d/www.conf`
- example php-fpm Dockerfile: `https://github.com/InvoicePlane/InvoicePlane/blob/development/resources/docker/php-fpm/Dockerfile` and yes, it's not the Alpine image
- example nginx Dockerfile: `https://github.com/InvoicePlane/InvoicePlane/blob/development/resources/docker/nginx/Dockerfile`

If I have a great example on which you worked, I can re-try to work on it next weekend.

**Comment by mhzawadi** [comment]
Hey @nielsdrost7 

Thanks for your reply, turns out I had dumped all the work I did. I have now uploaded the update  to my dev branch and an image is on the docker hub, it still fails with a session error.

```
2023-01-29 20:38:44 2023/01/29 20:38:44 [error] 14#14: *21 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of CI_SessionWrapper::open(string $save_path, string $name): bool must be compatible with SessionHandlerInterface::open($save_path, $name) in /var/www/html/vendor/codeigniter/framework/system/libraries/Session/PHP8SessionWrapper.php on line 59" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php.socket:", host: "127.0.0.1"
2023-01-29 20:38:44 127.0.0.1 - - [29/Jan/2023:20:38:44 +0000] "GET /index.php HTTP/1.1" 500 862 "-" "curl/7.87.0" "-"
```

I have the below installed, below that is what I cant install as Alpine donr have a package for it. I have run php info and found the json and hash are built-in.

installed:
- php81-gd
- php81-mbstring
- php81-mysqli
- php81-openssl
- php81-xml

cant install (not in alpine 3.17/PHP81)
- php81-hash
- php81-json
- php81-mcrypt
- php81-recode
- php81-xmlrpc

PHP Info
### mbstring
Multibyte Support => enabled
### json
json support => enabled
### hash
hash support => enabled
Hashing Engines => md2 md4 md5 sha1 sha224 sha256 sha384 sha512/224 sha512/256 sha512 sha3-224 sha3-256 sha3-384 sha3-512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b crc32c fnv132 fnv1a32 fnv164 fnv1a64 joaat murmur3a murmur3c murmur3f xxh32 xxh64 xxh3 xxh128 haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5

**Comment by nielsdrost7** [comment]
I couldn't get your branch to work, yet. Here are my steps to reproduce, so you can see what my experience was:
- a complete blank debian-like Linux distribution with Docker installed, of course
- git clone (your branch)
- docker-compose up -d
- Going to `localhost` or that `invoiceplane.docker.local` (after setting it in /etc/hosts) will result in a 404 error. Not the nginx, ugly one, but a complete white page with nice looking letters top left corner

- I edited the nginx_site.conf (whatever the Filename was), but I realized you used your own image from dkckerhub, so I had to adjust `docker-compose.yml` to look at local Dockerfile
- rebuild with force-rebuild (nice flag in docker-compose): `docker-compose up --force-rebuild -d`

**Comment by mhzawadi** [comment]
Hey, looks like you need some help.

if you have my branch checked out, run `docker build -t mhzawadi/invoiceplane:dev .` to build my image. 
Then just run `docker-compose up -d`, that should have a running setup with both traefik and mariadb.

I do wander if my issue would get sorted if codeigniter was updated to v4?

**Comment by nielsdrost7** [comment]
Hi,

So I have a follow-up of your bug-report:

_The good news_: I can reproduce your problem
_The bad news_: I still couldn't make your dev branch work with `docker-compose up -d`. I had to do the separate starting of MySQL and the InvoicePlane container. I'll send in a PR.
Maybe it can be resolved by eliminating the traefik proxy.

_More bad news_: Every time I had to make a change I had to re-build the image. When you want to develop something, like, for example editing the CodeIgniter code in the vendor directory :roll_eyes: ... that wouldn't be a great developer experience.
More bad news: The error you're experiencing and that I can reproduce ... comes from the CodeIgniter in the vendor folder: https://stackoverflow.com/questions/70508122/message-return-type-of-ci-session-files-driveropensave-path-name-should

_Good news_: I'll see if I can update CodeIgniter in the created image

I'll try to reproduce the problem with a default docker setup from InvoicePlane: git clone the `development` branch and then `docker-compose up -d`
I'll also try to implement your config files into the default InvoicePlane docker setup, so it's easier to reproduce your problem.

**Comment by mhzawadi** [comment]
Hey,

Thanks for your work in getting this sorted, I know this is not your issue per say.

I too have good news, I have updated my dev branch with a dev docker compose file `docker-compose -f docker-compose-dev.yml up -d`.

I have also been editing the CodeIgniter code and have got it to run, but you have to edit both `SessionHandlerInterface.php` and `PHP8SessionWrapper.php` to make then match up and work.

Do you want me to open an issue with CodeIgniter v3 and link to this issue? as I have working code for PHP8.1

in `PHP8SessionWrapper.php` you need to remoce the variable types on all the functions (e.g. `public function open($save_path, $name): bool`)

In `SessionHandlerInterface.php`
```
	#[\ReturnTypeWillChange] <- add this to every function
	public function open($save_path, $name);
	#[\ReturnTypeWillChange]
	public function close();
	#[\ReturnTypeWillChange]
	public function read($session_id);
	#[\ReturnTypeWillChange]
	public function write($session_id, $session_data);
	#[\ReturnTypeWillChange]
	public function destroy($session_id);
	#[\ReturnTypeWillChange]
	public function gc($maxlifetime);
```

**Comment by nielsdrost7** [comment]
Hi,
> Do you want me to open an issue with CodeIgniter v3 and link to this issue? as I have working code for PHP8.1

Sure, yes, please, that would be great. I'll look at docker-compose-dev.yml as soon as I can.

**Comment by mhzawadi** [comment]
Closing this as things now work in PHP8.1, not sure how or why.
My Dev image on the docker hub works and I have tested almost all functions, will spin up on my docker swarm and test emailing maybe next week.
