### ISSUE TITLE
Issue with vendor/autoload.php when trying to deploy with docker-compose.yaml

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [InvoicePlane/InvoicePlane#949]
Greetings,

 I try to test InvoicePlane, so I use the docker-compose.yaml provided at https://github.com/InvoicePlane/InvoicePlane/blob/development/docker-compose.yml .

All containers are up and running, however the setup page does not seem to be loading properly. Instead I receive a ` Failed opening required 'vendor/autoload.php' ` error.

## Expected Behavior
Access the setup page under http://server.domain.com/index.php/setup

## Current Behavior
All containers are up and running, however the setup page does not seem to be loading properly.
Instead I receive the following error when I access http://server.domain.com/index.php/setup from my browser:
```
Warning: require(vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/projects/invoiceplane/index.php on line 18

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/projects/invoiceplane/index.php:18 Stack trace: #0 {main} thrown in /var/www/projects/invoiceplane/index.php on line 18
```

## Screenshots
Docker containers:
![image](https://github.com/InvoicePlane/InvoicePlane/assets/13638976/f03909fd-5423-4995-91db-39803bf3d1e3)

Browser:
![image](https://github.com/InvoicePlane/InvoicePlane/assets/13638976/fda08f42-2521-417b-b97e-119981b58f7b)

## Steps to Reproduce

1. Clone the current directory.
2. Make a copy of the ipconfig.php.example file and rename it to ipconfig.php.
3. Edit ipconfig.php and set my URL (`IP_URL=http://server.domain.com`).
4. Execute `docker compose up -d`.
5. Enter http://server.domain.com/index.php/setup in my browser, as suggested.
6. Receive the `vendor/autoload.php` error above

## Context (Environment)
I tested this both on a `Red Hat Enterprise Linux 9` server as well as on a Windows environment.
In both cases I received the same error.

Thank you in advance

**Comment by EvgeniaPatsoni** [comment]
Hi @nielsdrost7 

Thanks for the rapid response.

I did as you suggested:
- Downloaded and unziped v1.6.0.zip
- Added ipconfig.php
- While in `ip` directory execute `docker-compose up -d`
- Again all 4 docker containers are up and running

However I now face a new error when I try to access http://server.domain.com/index.php/setup

`The <b>ipconfig.php</b> file is missing! Please make a copy of the <b>ipconfig.php.example</b> file and rename it to <b>ipconfig.php</b>[root@devops-test-1 ip]# curl 0.0.0.0:80
<br />
<b>Fatal error</b>:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [&lt;?php exit('No direct script access allowed'); ?&gt;]. in /var/www/projects/invoiceplane/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30
Stack trace:
#0 /var/www/projects/invoiceplane/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}('Encountered an ...')
#1 /var/www/projects/invoiceplane/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error-&gt;mapError(Object(Closure))
#2 /var/www/projects/invoiceplane/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser-&gt;parse('&lt;?php exit('No ...')
#3 /var/www/projects/invoiceplane/index.php(20): Dotenv\Dotenv-&gt;load()
#4 {main}
  thrown in <b>/var/www/projects/invoiceplane/vendor/vlucas/phpdotenv/src/Parser/Parser.php</b> on line <b>30</b><br />`

![image](https://github.com/InvoicePlane/InvoicePlane/assets/13638976/899e3908-aea4-4162-8b0e-568206880ede)

Not sure if I am missing something or doing something wrong...

Thank you once again

**Comment by nielsdrost7** [comment]
So ... in that `ip` directory, check if a file called `ipconfig.php` is present.

You said you added that `ipconfig.php` file, but double check if you added it in that `ip` directory.

Last thing you will run into is problems with the top line of the ipconfig.php file. For that, check this thread on the community foruma: https://community.invoiceplane.com/t/topic/10233/5

**Comment by EvgeniaPatsoni** [comment]
Yes the ipconfig.php file is present in the ip directory.
I actually had to commend out this line `# <?php exit('No direct script access allowed'); ?>` as mentioned here: https://wiki.invoiceplane.com/en/1.6/getting-started/updating-ip#160-2-replace-files

I can finally access the Setup page successfully.
However I am now stuck at the "Database Details" page, as it says it cannot connect to mariadb..But I might open a new issue for that if I can't figure it out.

Thank you for your help!
